### ISSUE TITLE
Exception during installation

### ISSUE THREAD

**Issue by nikscha** [keyz182/DuetMQTT#3]
Hi!
I'm getting an exception during installation:
When I run

/opt/DuetMQTT/DuetMQTT -s /var/run/dsf/dcs.sock -t "duet/Arges" -h 192.168.178.84:8123 --drop-thumbs --quiet

I get the following error:

Unhandled exception. MQTTnet.Exceptions.MqttCommunicationException: Error while connecting with host '192.168.178.84:8123:1883'.
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at DuetMQTT.Program.<>c.<<Main>b__1_0>d.MoveNext() in /home/runner/work/DuetMQTT/DuetMQTT/Program.cs:line 73
--- End of stack trace from previous location ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult1 result, Func2 action)
   at DuetMQTT.Program.Main(String[] args) in /home/runner/work/DuetMQTT/DuetMQTT/Program.cs:line 52
   at DuetMQTT.Program.<Main>(String[] args)
Aborted

I'm running home assistant on a Docker Image on my NAS

**Comment by keyz182** [comment]
You've got the port appended to the hostname `-h 192.168.178.84:8123` change that to `-h 192.168.178.84 -p 8123`.
